packages:
  - apps/*
  - packages/*
allowBuilds:
  '@nestjs/core': true
  esbuild: true
  lefthook: true
  msw: true
  sharp: true
  unrs-resolver: true
catalog:
  "@better-auth/expo": ^1.6.10
  "@tanstack/react-form": ^1.32.0
  "@tanstack/react-query": ^5.100.10
  "@ts-rest/core": ^3.52.1
  "@ts-rest/react-query": ^3.52.1
  "@types/node": ^25.6.2
  "@types/react": ^19.2.14
  "@vitest/coverage-v8": ^4.1.5
  "@vitest/ui": ^4.1.5
  better-auth: ^1.6.10
  dotenv: ^17.4.2
  jsdom: ^29.1.1
  msw: ^2.14.6
  react: ^19.2.6
  react-dom: ^19.2.6
  vitest: ^4.1.5
  zod: ^4.4.3
